const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { formatCurrency } = require('../utils/financialCalculator');

const HEADER_HEIGHT = 100;
const COLORS = {
  background: '#f8fafc',
  surface: '#ffffff',
  text: '#111827',
  muted: '#475569',
  primary: '#2563eb',
  success: '#10b981',
  warning: '#f97316',
  border: '#e2e8f0',
  accent: '#8b5cf6',
};

const addSectionTitle = (doc, title) => {
  const y = doc.y;
  doc.fill(COLORS.primary).fontSize(12).font('Helvetica-Bold').text(title, { align: 'left' });
  doc.moveDown(0.2);
  doc.strokeColor(COLORS.border).lineWidth(1).moveTo(doc.page.margins.left, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.6);
};

const addHeader = (doc, title, monthLabel, generatedAt) => {
  doc.rect(0, 0, doc.page.width, 120).fill(COLORS.primary);
  doc.fill('#ffffff').fontSize(18).font('Helvetica-Bold').text('PHARMORA BUSINESS MANAGER', 50, 28, { align: 'left' });
  doc.fontSize(12).font('Helvetica').text('Monthly Financial Report', 50, 52, { align: 'left' });
  doc.fontSize(9).fill('#dbeafe').text(`Report Month: ${monthLabel}`, 50, 72, { align: 'left' });
  doc.text(`Generated: ${generatedAt}`, 50, 86, { align: 'left' });
  doc.fontSize(9).fill('#dbeafe').text(title, doc.page.width - doc.page.margins.right - 180, 28, { align: 'right', width: 180 });
  doc.moveDown(6);
  doc.fill(COLORS.text);
};

const addFooter = (doc, pageNo, totalPages) => {
  const footerY = doc.page.height - doc.page.margins.bottom + 10;
  doc.fontSize(9).fill('#6b7280');
  doc.text(`Generated by Pharmora Business Manager`, doc.page.margins.left, footerY, { align: 'left' });
  doc.text(`Page ${pageNo} of ${totalPages}`, doc.page.margins.left, footerY, { align: 'right' });
};

const addSummaryCards = (doc, summary) => {
  const cards = [
    { title: 'Total Sales', value: formatCurrency(summary.totalSales), color: COLORS.primary },
    { title: 'Total Income', value: formatCurrency(summary.totalIncome), color: COLORS.success },
    { title: 'Total Expenses', value: formatCurrency(summary.totalExpenses), color: COLORS.warning },
    { title: 'Net Profit', value: formatCurrency(summary.netProfit), color: COLORS.accent },
    { title: 'Cash Received', value: formatCurrency(summary.cashReceived), color: COLORS.success },
    { title: 'Cash Paid', value: formatCurrency(summary.cashPaid), color: COLORS.warning },
    { title: 'Closing Cash', value: formatCurrency(summary.closingCash), color: COLORS.primary },
    { title: 'Closing Bank', value: formatCurrency(summary.closingBank), color: COLORS.accent },
  ];

  const x = doc.page.margins.left;
  const cardWidth = (doc.page.width - doc.page.margins.left - doc.page.margins.right - 24) / 4;
  let y = doc.y;

  cards.forEach((card, index) => {
    const rowIndex = Math.floor(index / 4);
    const colIndex = index % 4;
    const cardX = x + colIndex * (cardWidth + 12);
    const cardY = y + rowIndex * 90;

    if (cardY + 80 > doc.page.height - doc.page.margins.bottom - 50) {
      doc.addPage();
      addHeader(doc, '', '', '');
      addSectionTitle(doc, 'Key Monthly Metrics');
      y = doc.y;
    }

    doc.save();
    doc.roundedRect(cardX, cardY, cardWidth, 80, 10).fill('#ffffff').stroke(COLORS.border);
    doc.restore();

    doc.fill(card.color).fontSize(10).font('Helvetica-Bold').text(card.title, cardX + 12, cardY + 12, { width: cardWidth - 24 });
    doc.fill(COLORS.text).fontSize(16).font('Helvetica-Bold').text(card.value, cardX + 12, cardY + 35, { width: cardWidth - 24 });
  });

  doc.moveDown(8);
};

const drawTable = (doc, columns, rows, startY) => {
  const availableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const columnWidth = availableWidth / columns.length;
  let y = startY;

  const renderHeader = () => {
    doc.fontSize(9).font('Helvetica-Bold').fill(COLORS.text);
    columns.forEach((col, index) => {
      doc.text(col.label, doc.page.margins.left + index * columnWidth, y, {
        width: columnWidth,
        align: 'left',
      });
    });
    y += 18;
    doc.strokeColor(COLORS.border).lineWidth(0.5)
      .moveTo(doc.page.margins.left, y - 4)
      .lineTo(doc.page.width - doc.page.margins.right, y - 4)
      .stroke();
  };

  renderHeader();

  rows.forEach((row, rowIndex) => {
    doc.fontSize(8).font('Helvetica');

    const rowHeights = columns.map((col) => {
      const text = row[col.key] ? row[col.key].toString() : '-';
      return doc.heightOfString(text, { width: columnWidth, align: 'left' });
    });
    const rowHeight = Math.max(18, ...rowHeights) + 4;

    if (y + rowHeight > doc.page.height - doc.page.margins.bottom - 20) {
      doc.addPage({ layout: doc.page.layout });
      addHeader(doc, '', '', '');
      y = doc.y + 10;
      renderHeader();
    }

    if (row.backgroundColor) {
      doc.save();
      doc.rect(doc.page.margins.left, y - 2, availableWidth, rowHeight).fill(row.backgroundColor);
      doc.restore();
    } else if (rowIndex % 2 === 0) {
      doc.save();
      doc.rect(doc.page.margins.left, y - 2, availableWidth, rowHeight).fill('#f8fafc');
      doc.restore();
    }

    columns.forEach((col, colIndex) => {
      const value = row[col.key] ?? '-';
      doc.fill(COLORS.text).text(value.toString(), doc.page.margins.left + colIndex * columnWidth, y, {
        width: columnWidth,
        align: 'left',
        lineBreak: true,
      });
    });

    y += rowHeight;
  });

  return y;
};

const generateReportPdf = async ({
  monthLabel,
  reportMonth,
  generatedAt,
  summary,
  daySummary,
  transactions,
  analysis,
  charts,
  reportNumber,
  outputPath,
}) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
    const stream = fs.createWriteStream(outputPath);

    doc.pipe(stream);

    addHeader(doc, reportNumber, monthLabel, generatedAt);
    addSectionTitle(doc, 'Executive Summary');
    addSummaryCards(doc, summary);
    doc.addPage();

    addHeader(doc, reportNumber, monthLabel, generatedAt);
    addSectionTitle(doc, 'Day Wise Summary');
    doc.moveDown(0.4);

    const dayColumns = [
      { label: 'Date', key: 'date' },
      { label: 'Total', key: 'totalSales' },
      { label: 'Income', key: 'income' },
      { label: 'Expense', key: 'expense' },
      { label: 'Purchases', key: 'purchases' },
      { label: 'Cash In', key: 'cashIn' },
      { label: 'Cash Out', key: 'cashOut' },
      { label: 'Closing Cash', key: 'closingCash' },
      { label: 'Bank Balance', key: 'runningBank' },
    ];

    const formattedDayRows = daySummary.map((row) => ({
      date: row.date,
      totalSales: formatCurrency(row.totalSales),
      income: formatCurrency(row.income),
      expense: formatCurrency(row.expense),
      purchases: formatCurrency(row.purchases),
      cashIn: formatCurrency(row.cashIn),
      cashOut: formatCurrency(row.cashOut),
      closingCash: formatCurrency(row.closingCash),
      runningBank: formatCurrency(row.runningBank),
      backgroundColor: row.isWeekend ? '#f3f4f6' : null,
    }));

    drawTable(doc, dayColumns, formattedDayRows, doc.y + 10);
    doc.addPage();

    doc.addPage({ layout: 'landscape' });
    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.fontSize(12).fill('#111827').font('Helvetica-Bold').text('Complete Transaction History', { underline: true });
    doc.moveDown(0.4);

    const transactionColumns = [
      { label: 'Date', key: 'date' },
      { label: 'Type', key: 'type' },
      { label: 'Category', key: 'category' },
      { label: 'Details', key: 'description' },
      { label: 'In', key: 'moneyIn' },
      { label: 'Out', key: 'moneyOut' },
      { label: 'Bank Bal', key: 'runningBank' },
      { label: 'Created By', key: 'createdBy' },
    ];

    const formattedTransactions = transactions.map((txn) => ({
      date: txn.date,
      type: txn.type,
      category: txn.category,
      description: txn.description,
      moneyIn: txn.moneyIn ? formatCurrency(txn.moneyIn) : '-',
      moneyOut: txn.moneyOut ? formatCurrency(txn.moneyOut) : '-',
      runningBank: formatCurrency(txn.runningBank),
      createdBy: txn.createdBy,
      backgroundColor: txn.isWeekend ? '#f3f4f6' : null,
    }));

    drawTable(doc, transactionColumns, formattedTransactions, doc.y + 10);
    doc.addPage();

    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.fontSize(12).fill('#111827').font('Helvetica-Bold').text('Financial Analysis', { underline: true });
    doc.moveDown(0.4);

    const analysisRows = [
      ['Highest Sales Day', analysis.highestSalesDay],
      ['Lowest Sales Day', analysis.lowestSalesDay],
      ['Highest Expense Day', analysis.highestExpenseDay],
      ['Average Daily Sales', formatCurrency(analysis.averageDailySales)],
      ['Average Daily Expense', formatCurrency(analysis.averageDailyExpense)],
      ['Total Cash Received', formatCurrency(analysis.totalCashReceived)],
      ['Total Cash Paid', formatCurrency(analysis.totalCashPaid)],
      ['Purchase Percentage', analysis.purchasePercentage],
      ['Expense Percentage', analysis.expensePercentage],
      ['Net Profit', formatCurrency(analysis.netProfit)],
      ['Profit Margin', analysis.profitMargin],
    ];

    analysisRows.forEach(([label, value]) => {
      doc.fontSize(10).font('Helvetica-Bold').fill('#111827').text(label, { continued: true });
      doc.font('Helvetica').fill('#111827').text(`: ${value}`);
      doc.moveDown(0.15);
    });

    doc.addPage();
    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.fontSize(12).fill('#111827').font('Helvetica-Bold').text('Charts', { underline: true });
    doc.moveDown(0.4);

    if (charts.dailySales) {
      const yBefore = doc.y;
      doc.image(charts.dailySales, { fit: [500, 280], align: 'center' });
      doc.moveDown(2);
    }

    if (charts.dailyExpenses) {
      doc.image(charts.dailyExpenses, { fit: [500, 280], align: 'center' });
      doc.moveDown(2);
    }

    if (charts.paymentMethods) {
      doc.image(charts.paymentMethods, { fit: [500, 280], align: 'center' });
    }

    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(i);
      addFooter(doc, i + 1, range.count);
    }

    doc.end();

    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
};

module.exports = {
  generateReportPdf,
};