const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { formatCurrency } = require('../utils/financialCalculator');

const HEADER_HEIGHT = 100;

const addHeader = (doc, title, monthLabel, generatedAt) => {
  doc.fill('#111827').fontSize(20).font('Helvetica-Bold').text('PHARMORA BUSINESS MANAGER', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(16).font('Helvetica').fill('#4b5563').text('Monthly Financial Report', { align: 'center' });
  doc.moveDown(0.4);
  doc.fontSize(10).fill('#6b7280');
  doc.text(`Report Month: ${monthLabel}`, { align: 'center' });
  doc.text(`Generated: ${generatedAt}`, { align: 'center' });
  doc.moveDown(0.6);
  doc.strokeColor('#e5e7eb').lineWidth(1).moveTo(doc.page.margins.left, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).stroke();
  doc.moveDown(0.8);
};

const addFooter = (doc, pageNo, totalPages) => {
  const footerY = doc.page.height - doc.page.margins.bottom + 10;
  doc.fontSize(9).fill('#6b7280');
  doc.text(`Generated by Pharmora Business Manager`, doc.page.margins.left, footerY, { align: 'left' });
  doc.text(`Page ${pageNo} of ${totalPages}`, doc.page.margins.left, footerY, { align: 'right' });
};

const addSummaryCards = (doc, summary) => {
  const cards = [
    { title: 'Total Sales', value: formatCurrency(summary.totalSales) },
    { title: 'Cash Sales', value: formatCurrency(summary.cashSales) },
    { title: 'UPI Sales', value: formatCurrency(summary.upiSales) },
    { title: 'Bank Sales', value: formatCurrency(summary.bankSales) },
    { title: 'Credit Sales', value: formatCurrency(summary.creditSales) },
    { title: 'Total Income', value: formatCurrency(summary.totalIncome) },
    { title: 'Total Expenses', value: formatCurrency(summary.totalExpenses) },
    { title: 'Total Purchases', value: formatCurrency(summary.totalPurchases) },
    { title: 'Distributor Payments', value: formatCurrency(summary.distributorPayments) },
    { title: 'Cash Received', value: formatCurrency(summary.cashReceived) },
    { title: 'Cash Paid', value: formatCurrency(summary.cashPaid) },
    { title: 'Opening Cash', value: formatCurrency(summary.openingCash) },
    { title: 'Closing Cash', value: formatCurrency(summary.closingCash) },
    { title: 'Opening Bank Balance', value: formatCurrency(summary.openingBank) },
    { title: 'Closing Bank Balance', value: formatCurrency(summary.closingBank) },
    { title: 'Net Profit', value: formatCurrency(summary.netProfit) },
    { title: 'Net Cash Flow', value: formatCurrency(summary.netCashFlow) },
    { title: 'Total Transactions', value: summary.totalTransactions.toString() },
  ];

  const x = doc.page.margins.left;
  const cardWidth = (doc.page.width - doc.page.margins.left - doc.page.margins.right - 24) / 3;
  let y = doc.y;

  cards.forEach((card, index) => {
    const rowIndex = Math.floor(index / 3);
    const colIndex = index % 3;
    const cardX = x + colIndex * (cardWidth + 12);
    const cardY = y + rowIndex * 80;

    if (cardY + 70 > doc.page.height - doc.page.margins.bottom - 50) {
      doc.addPage();
      addHeader(doc, '', '', '');
      y = doc.y;
    }

    doc.save();
    doc.roundedRect(cardX, cardY, cardWidth, 70, 8).fill('#f8fafc');
    doc.restore();

    doc.fill('#111827').fontSize(10).font('Helvetica-Bold').text(card.title, cardX + 10, cardY + 10, { width: cardWidth - 20 });
    doc.fill('#111827').fontSize(14).font('Helvetica').text(card.value, cardX + 10, cardY + 30, { width: cardWidth - 20 });
  });

  doc.moveDown(6);
};

const drawTable = (doc, columns, rows, startY) => {
  const columnWidth = (doc.page.width - doc.page.margins.left - doc.page.margins.right) / columns.length;
  let y = startY;

  doc.fontSize(9).font('Helvetica-Bold');
  columns.forEach((col, index) => {
    doc.fill('#111827').text(col.label, doc.page.margins.left + index * columnWidth, y, { width: columnWidth, align: 'left' });
  });
  y += 18;

  rows.forEach((row, rowIndex) => {
    if (y > doc.page.height - doc.page.margins.bottom - 40) {
      doc.addPage();
      addHeader(doc, '', '', '');
      y = doc.y + 10;
      doc.fontSize(9).font('Helvetica-Bold');
      columns.forEach((col, index) => {
        doc.text(col.label, doc.page.margins.left + index * columnWidth, y, { width: columnWidth, align: 'left' });
      });
      y += 18;
    }

    rows[rowIndex].backgroundColor = row.backgroundColor || null;
    if (row.backgroundColor) {
      doc.rect(doc.page.margins.left, y - 2, doc.page.width - doc.page.margins.left - doc.page.margins.right, 18)
        .fill(row.backgroundColor)
        .fillColor('#111827');
    }

    doc.fontSize(8).font('Helvetica');
    columns.forEach((col, colIndex) => {
      const value = row[col.key] ?? '-';
      doc.fill('#111827').text(value.toString(), doc.page.margins.left + colIndex * columnWidth, y, { width: columnWidth, align: 'left' });
    });
    y += 18;
  });

  return y;
};

const generateReportPdf = async ({
  monthLabel,
  reportMonth,
  generatedAt,
  summary,
  daySummary,
  transactions,
  analysis,
  charts,
  reportNumber,
  outputPath,
}) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
    const stream = fs.createWriteStream(outputPath);

    doc.pipe(stream);

    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.moveDown(1);
    addSummaryCards(doc, summary);
    doc.addPage();

    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.moveDown(1);
    doc.fontSize(12).fill('#111827').font('Helvetica-Bold').text('Day Wise Summary', { underline: true });
    doc.moveDown(0.4);

    const dayColumns = [
      { label: 'Date', key: 'date' },
      { label: 'Cash Sales', key: 'cashSales' },
      { label: 'UPI Sales', key: 'upiSales' },
      { label: 'Bank Sales', key: 'bankSales' },
      { label: 'Credit Sales', key: 'creditSales' },
      { label: 'Total Sales', key: 'totalSales' },
      { label: 'Income', key: 'income' },
      { label: 'Expense', key: 'expense' },
      { label: 'Purchases', key: 'purchases' },
      { label: 'Distributor Payment', key: 'distributorPayments' },
      { label: 'Cash In', key: 'cashIn' },
      { label: 'Cash Out', key: 'cashOut' },
      { label: 'Opening Cash', key: 'openingCash' },
      { label: 'Closing Cash', key: 'closingCash' },
      { label: 'Running Bank', key: 'runningBank' },
    ];

    const formattedDayRows = daySummary.map((row) => ({
      date: row.date,
      cashSales: formatCurrency(row.cashSales),
      upiSales: formatCurrency(row.upiSales),
      bankSales: formatCurrency(row.bankSales),
      creditSales: formatCurrency(row.creditSales),
      totalSales: formatCurrency(row.totalSales),
      income: formatCurrency(row.income),
      expense: formatCurrency(row.expense),
      purchases: formatCurrency(row.purchases),
      distributorPayments: formatCurrency(row.distributorPayments),
      cashIn: formatCurrency(row.cashIn),
      cashOut: formatCurrency(row.cashOut),
      openingCash: formatCurrency(row.openingCash),
      closingCash: formatCurrency(row.closingCash),
      runningBank: formatCurrency(row.runningBank),
      backgroundColor: row.isWeekend ? '#f3f4f6' : null,
    }));

    drawTable(doc, dayColumns, formattedDayRows, doc.y + 10);
    doc.addPage();

    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.fontSize(12).fill('#111827').font('Helvetica-Bold').text('Complete Transaction History', { underline: true });
    doc.moveDown(0.4);

    const transactionColumns = [
      { label: 'Date', key: 'date' },
      { label: 'Time', key: 'time' },
      { label: 'Type', key: 'type' },
      { label: 'Category', key: 'category' },
      { label: 'Description', key: 'description' },
      { label: 'Payment Mode', key: 'paymentMode' },
      { label: 'Reference', key: 'referenceNo' },
      { label: 'Money In', key: 'moneyIn' },
      { label: 'Money Out', key: 'moneyOut' },
      { label: 'Cash Balance', key: 'runningCash' },
      { label: 'Bank Balance', key: 'runningBank' },
      { label: 'Created By', key: 'createdBy' },
    ];

    const formattedTransactions = transactions.map((txn) => ({
      date: txn.date,
      time: txn.time,
      type: txn.type,
      category: txn.category,
      description: txn.description,
      paymentMode: txn.paymentMode,
      referenceNo: txn.referenceNo || '-',
      moneyIn: txn.moneyIn ? formatCurrency(txn.moneyIn) : '-',
      moneyOut: txn.moneyOut ? formatCurrency(txn.moneyOut) : '-',
      runningCash: formatCurrency(txn.runningCash),
      runningBank: formatCurrency(txn.runningBank),
      createdBy: txn.createdBy,
      backgroundColor: txn.isWeekend ? '#f3f4f6' : null,
    }));

    drawTable(doc, transactionColumns, formattedTransactions, doc.y + 10);
    doc.addPage();

    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.fontSize(12).fill('#111827').font('Helvetica-Bold').text('Financial Analysis', { underline: true });
    doc.moveDown(0.4);

    const analysisRows = [
      ['Highest Sales Day', analysis.highestSalesDay],
      ['Lowest Sales Day', analysis.lowestSalesDay],
      ['Highest Expense Day', analysis.highestExpenseDay],
      ['Average Daily Sales', formatCurrency(analysis.averageDailySales)],
      ['Average Daily Expense', formatCurrency(analysis.averageDailyExpense)],
      ['Total Cash Received', formatCurrency(analysis.totalCashReceived)],
      ['Total Cash Paid', formatCurrency(analysis.totalCashPaid)],
      ['Purchase Percentage', analysis.purchasePercentage],
      ['Expense Percentage', analysis.expensePercentage],
      ['Net Profit', formatCurrency(analysis.netProfit)],
      ['Profit Margin', analysis.profitMargin],
    ];

    analysisRows.forEach(([label, value]) => {
      doc.fontSize(10).font('Helvetica-Bold').fill('#111827').text(label, { continued: true });
      doc.font('Helvetica').fill('#111827').text(`: ${value}`);
      doc.moveDown(0.15);
    });

    doc.addPage();
    addHeader(doc, reportNumber, monthLabel, generatedAt);
    doc.fontSize(12).fill('#111827').font('Helvetica-Bold').text('Charts', { underline: true });
    doc.moveDown(0.4);

    if (charts.dailySales) {
      const yBefore = doc.y;
      doc.image(charts.dailySales, { fit: [500, 280], align: 'center' });
      doc.moveDown(2);
    }

    if (charts.dailyExpenses) {
      doc.image(charts.dailyExpenses, { fit: [500, 280], align: 'center' });
      doc.moveDown(2);
    }

    if (charts.paymentMethods) {
      doc.image(charts.paymentMethods, { fit: [500, 280], align: 'center' });
    }

    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(i);
      addFooter(doc, i + 1, range.count);
    }

    doc.end();

    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
};

module.exports = {
  generateReportPdf,
};